[Settings]
ID = "0b8b4101-fb86-48bd-bed7-e15bbdda6226"

[build]
    functions = "./functions"
    CI= "npm run build"

    # If skip_processing = true, all other settings are ignored
    [build.processing]
        skip_processing = false
    [build.processing.css]
        bundle = true
        minify = true
    [build.processing.js]
        bundle = true
        minify = true
    [build.processing.html]
        pretty_urls = true
    [build.processing.images]
        compress = true

[dev]
    publish = "src/"
    functions = "functions/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    # Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Content-Security-Policy = "frame-ancestors https://www.facebook.com"

    # Multi-value headers are expressed with multi-line strings.
	  # cache-control = '''
	  # max-age=0,
	  # no-cache,
	  # no-store,
	  # must-revalidate'''


[functions]
    directory = "functions/"

[[redirects]]
    from = "/*"
    to = "/.netlify/functions/app"
    status = 301
    force = true # COMMENT: ensure that we always redirect